spring:
  data:
    mongodb:
      uri: ${{MONGODB_URI}}
  jackson:
    serialization:
      wrap-root-value: true
springdoc:
  api-docs:
    path: api-docs
com:
  gescof:
    calculator:
      api:
        basePath: api/v1/calculator
        sumPath: sum
        subtractionPath: subtraction
        multiplicationPath: multiplication
        divisionPath: division
        operationsPath: operations
